### ISSUE TITLE
tech-database: mongodb about.md

### ISSUE THREAD

**Issue by mahtjarohst** [developer-portal/content#453] opened 2022-09-14 22:00 UTC
Unable to find a match: mongodb mongodb-server

If the repo is no longer available, please remove this from the portal. Or if I am making a mistake, fix the documentation so that it makes sense.

**Comment by jackorp** [comment] 2022-10-04 10:06
MongoDB is not available in Fedora for some time, therefore I have removed the section. AFAICT only 4.4 is the latest that will install without major problems from upstream repos.

Closing as duplicate of https://github.com/developer-portal/content/issues/426 .
Will be fixed by https://github.com/developer-portal/content/pull/456 .

**Closed by jackorp** 2022-10-04 10:06 UTC
