### ISSUE TITLE
: web-app rails.md

### ISSUE THREAD

**Issue by dirschn** [developer-portal/content#494] opened 2023-11-28 22:48 UTC
I noticed today that the Ruby on Rails guide mentions
> Whenever you install a new version of Ruby or a gem, you should run the rehash sub-command. This will make rails executables known to rbenv, which will allow us to run those executables:

I was a little confused because I haven't manually run that  command ever and haven't had any issues, so I took a look at the [rbenv GitHub page](https://github.com/rbenv/rbenv) and in the [`rbenv rehash`](https://github.com/rbenv/rbenv#rbenv-rehash) section it mentions that `rbenv rehash` is run automatically when installing gems. It seems to me that there's no need to run it manually after installing new versions or gems?

Apologies if I have the format of creating a new issue wrong, I couldn't find any format requirements!

**Comment by jackorp** [comment] 2023-11-29 11:22
Thanks for taking time sharing this!

Yeah we were discussing this recently on some rbenv related pull request whether that's needed, we left it there due to not being sure. Thanks for finding the reference that it isn't needed, We can fix that with confidence now.

Alternatively, you can edit the page yourself here: https://github.com/developer-portal/content/blob/master/start/sw/web-app/rails.md , we have some related info for contributing here: https://developer-portal.github.io/contributing/

**Comment by benmelz** [comment] 2023-11-29 17:10
Coworker of @dirschn here, with a small gotcha. I'm observing with `rbenv 1.2.0-80-gd6bb1c6` that while `gem install` appears to trigger automatic rehashing, `bundle` does not.

We include the following in our setup script and haven't added cli tools in a while, hence @dirschn's confusion
```ruby
  system('bundle check') || system!('bundle install')
  system('if command -v rbenv &> /dev/null; then rbenv rehash; fi')
```

Since the majority of rails devs will be installing tools via `bundle`, that might warrant leaving this section in for now at least (perhaps open an issue with the rbenv team to expand functionality to `bundle`? and then this could be removed).

**Comment by jackorp** [comment] 2023-11-30 00:27
Huh, that's interesting behavior. So to get my mental notes on this straight:

The following triggers a rehash:
```
gem install foo-bar-with-executable
```

While the following command in a project with a Gemfile containing entry for gem `foo-bar-with-executable`:
```
bundle install
```
will not then execute rehash and therefore `foo-bar-with-executable` will not be available correctly?

I am a little bit confused as I have not yet had the need for bundler + rbenv combo,
is it regularly expected that bundle install would make `foo-bar-with-executable` available on regular path with rbenv after a rehash?

A rewording or similar might be warranted though if it works for all but bundler environments.

**Comment by benmelz** [comment] 2023-11-30 15:40
> Huh, that's interesting behavior. So to get my mental notes on this straight:
> 
> The following triggers a rehash:
> 
> ```
> gem install foo-bar-with-executable
> ```
> 
> While the following command in a project with a Gemfile containing entry for gem `foo-bar-with-executable`:
> 
> ```
> bundle install
> ```
> 
> will not then execute rehash and therefore `foo-bar-with-executable` will not be available correctly?

Yes this is all correct (at least, that's what I'm observing on my machine). To reproduce, you can manually remove shims from `${RBENV_ROOT}/shims` and watch if they're regenerated when using `gem install` vs `bundle install`.

> I am a little bit confused as I have not yet had the need for bundler + rbenv combo, is it regularly expected that bundle install would make `foo-bar-with-executable` available on regular path with rbenv after a rehash?
> 
> A rewording or similar might be warranted though if it works for all but bundler environments.

The wording in their documentation is a little ambiguous (it says "it will run automatically after installing gems" which could be interpreted either way).

That being said, I looked into it a little this morning and found that there's [code that's _meant_ to extend the functionality to bundler](https://github.com/rbenv/rbenv/blob/d10388a0529cb4f05b170395bb01c257a8186062/rbenv.d/exec/gem-rehash/rubygems_plugin.rb#L13), but when I put in some debugging statements it appears that the plugin isn't getting loaded for `bundle`.

i.e. it seems that their intention is for both to apply and it's actually a bug that it doesnt

**Comment by benmelz** [comment] 2023-11-30 19:14
> Huh, that's interesting behavior. So to get my mental notes on this straight:
> 
> The following triggers a rehash:
> 
> ```
> gem install foo-bar-with-executable
> ```
> 
> While the following command in a project with a Gemfile containing entry for gem `foo-bar-with-executable`:
> 
> ```
> bundle install
> ```
> 
> will not then execute rehash and therefore `foo-bar-with-executable` will not be available correctly?

Yes that's correct.

> I am a little bit confused as I have not yet had the need for bundler + rbenv combo, is it regularly expected that bundle install would make `foo-bar-with-executable` available on regular path with rbenv after a rehash?
> 
> A rewording or similar might be warranted though if it works for all but bundler environments.

So after some more investigation, I've figured out that this is in fact a bug with `rbenv` - https://github.com/rbenv/rbenv/issues/1540 (i.e. there is code for automatic rehashing specifically for `bundle install`, but it doesn't work).

**Comment by benmelz** [comment] 2023-12-11 19:52
Update: patch has been accepted and merged in [`rbenv/rbenv:master`](https://github.com/rbenv/rbenv/commit/325abac17de79a230152bb7038126a0641c6aa64) so _now_ this issue as initially described is accurate, assuming an up-to-date rbenv.

I'll caution that there hasn't been an "official" release of `rbenv` in 2 years so it's likely only people who install via git will get it for a while (depending on the different package manager formulae definitions).

**Comment by jackorp** [comment] 2023-12-12 09:34
Thanks! I think it should now be adjusted to say to either update rbenv (with reference to either this discussion or rather the upstream PR) if pulled via git by user or state that in the other case the rehash is needed for `bundler install` :)
Either way, we have an answer for whether it's needed, if any of you would manage to write something up, I'd immensely appreciate it.

**Comment by jackorp** [comment] 2023-12-20 10:58
I have created #498, I also fixed up the styling and whatnot on the page. If you want to, you can check the section regarding rbenv on the PR and review it.

**Comment by dirschn** [comment] 2023-12-20 15:15
That's my bad, it was a busy week and this slipped my mind. I'll take a look when I get home from work.

**Closed** 2024-01-02 08:34 UTC

**Comment by jackorp** [comment] 2024-01-02 08:39
Thanks to you both, for helping with reviews, collaboration, and reporting/fixing the bug upstream. All of these contributions are very much appreciated.
