### ISSUE TITLE
Software Collections

### ISSUE THREAD

**Issue by asamalik** [developer-portal/content#17] opened 2015-07-28 14:49 UTC

**Comment by strzibny** [comment] 2015-08-10 07:05
Software Collections are not part of Fedora as of now.

**Comment by bkabrda** [comment] 2015-08-10 07:09
It is, however, a technology that is usable on Fedora and used in some COPR repos. So while it should clearly be documented that SCLs are not available through official Fedora repos, describing SCLs in general is IMO a good idea.

**Comment by strzibny** [comment] 2015-08-10 07:14
Yes, but... what will be content of this pages? Creating SCLs should be documented upstream in my opinion. I am not saying the the portal cannot grow into something bigger in future, but covering things that are not in Fedora and not related to Fedora (deployment to OpenShift) I currently see as problematic.

**Comment by bkabrda** [comment] 2015-08-10 07:15
In my mind, this should be something very simple, saying:
- What are SCLs
- How to use them
- Where to get them (some copr repos/softwarecollections.org)
- Link to upstream documentation

1 page of text, tops.

**Comment by strzibny** [comment] 2015-08-10 07:23
For me one paragraph with a link should be everything needed. We should cover Fedora specifics not do duplicate work. And if upstream documentation is not enough, let's improve that one.

(Yes I am trying very hard to limit the scope of this project because I want to publish something we can actually maintain.)

**Comment by hhorak** [comment] 2015-08-11 07:20
Well, it may be quite unclear that scl.org is actually the only place where collections for Fedora may be advertised currently or even that this site includes also Fedora packages. So, I'd focus on something like this:
* Wanna create SCL for Fedora? Do that, that and that (build it in copr and advertise on scl.org)
* Seeking for SCL for Fedora? Go to ... and search for ...

**Comment by phracek** [comment] 2015-08-31 14:26
I guess so. If you would like to create a something for SCL to this, ...
If some steps describe what should be done I would be glad.

**Comment by pvalena** [comment] 2016-10-14 13:25
I'm closing this, because [1] do not mention Fedora at all.

[1] https://www.softwarecollections.org

**Closed by pvalena** 2016-10-14 13:25 UTC
Labels: Section: Deploy and Distribute, Status: Help Needed

**Comment by hhorak** [comment] 2016-10-14 14:16
> I'm closing this, because [1] do not mention Fedora at all.
> 
> [1] https://www.softwarecollections.org

But it could :) I think it still makes sense to help people to deliver this awesome technology on Fedora, outside of distribution, but still... SCL builds from copr are technically fine enough for softwarecollections.org..

**Comment by pvalena** [comment] 2016-10-14 14:45
@hhorak, for me the issue is that there is no documentation/upstream/activity for SCL on Fedora that I know of we could point people to. I do not think it's wise to have an 'upstream' for SCL on Fedora on developer-portal. We do not think we could handle all the issues with it.

**Comment by hhorak** [comment] 2016-10-14 14:56
I don't think it means any significant work for developer portal, what I'd like to see though is something along these lines:

* "Do you want to have more versions of one package on one system? that's what SCLs are for."
* now 3 paragraphs of principles
* something about new version of scl-utils package in Fedora
* link to packaging guide on scl.org
* example copr build of one simple collection
* "For more guidance and help reach out to sclorg@redhat.com ML."

That all under "More versions installed in parallel" or similarly generic page title.

**Comment by pvalena** [comment] 2016-10-14 15:18
I agree that It makes sense to include multiple-package-versions topic, as it affects developer's environment greatly. So maybe it could be under "Deploy and Distribute"? @asamalik, @phracek, what do you think?

**Comment by strzibny** [comment] 2016-10-14 15:23
I think we are beyond the initial bootstrapping so including well-maintained coprs and SCLs are no issue for me.
